databases:
  - name: ml_django
    databaseName: ml_django
    user: ml_django

services:
  - type: web
    name: ml_django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ml_django.wsgi:application"
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: ml_django
      #     property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
