databases:
  - name: paybuddybe
    databaseName: paybuddybe
    user: paybuddybe

services:
  - type: web
    name: paybuddybe
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn paybuddybe.wsgi:application"
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: paybuddybe
      #     property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
